#!/bin/bash

# Define the files to remove
# These are the main files generated by a typical C# console project
FILES=("EchoAppCSharp.csproj" "Program.cs")

# Inform the user which files are about to be deleted
echo "You are about to remove the following files:"
for file in "${FILES[@]}"; do
    echo "  - $file"
done

# Prompt the user for confirmation before proceeding
read -p "Are you sure you want to proceed? (y/N) " confirm

# Check if the user's response indicates confirmation
if [[ "$confirm" =~ ^[Yy]$ ]]; then
    # Iterate over the files and remove each one if it exists
    for file in "${FILES[@]}"; do
        if [[ -e "$file" ]]; then
            echo "Removing $file..."
            rm "$file"
        else
            echo "File not found: $file"
        fi
    done
    echo "Done."  # All deletions attempted
else
    # If the user declined, cancel the operation
    echo "Operation cancelled."
fi
